[package]
name = "rama-net-apple-networkextension"
description = "Apple Network Extension support for rama"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
keywords = ["io", "async", "non-blocking", "network", "rama"]
categories = ["asynchronous", "network-programming", "api-bindings", "security"]
authors = { workspace = true }
rust-version = { workspace = true }

[package.metadata.cargo-public-api-crates]
allowed = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []

[dependencies]
rama-core = { workspace = true }
rama-macros = { workspace = true }
rama-net = { workspace = true }
rama-tcp = { workspace = true }
rama-utils = { workspace = true }
tokio = { workspace = true, features = ["io-util", "rt-multi-thread", "sync"] }
pin-project-lite = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
parking_lot = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
tokio-test = { workspace = true }

[lints]
workspace = true
