[package]
name = "rama-tls-boring"
description = "tls implementations for rama using boring"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
keywords = ["io", "async", "tls", "network", "rama"]
categories = ["asynchronous", "network-programming", "cryptography", "web-programming"]
authors = { workspace = true }
rust-version = { workspace = true }

[package.metadata.cargo-public-api-crates]
allowed = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
http = ["dep:rama-http-types"]
compression = ["dep:flate2", "dep:brotli", "dep:zstd"]
ua = ["dep:rama-ua"]

[dependencies]
ahash = { workspace = true }
brotli = { workspace = true, optional = true }
flate2 = { workspace = true, optional = true }
flume = { workspace = true, features = ["async"] }
itertools = { workspace = true }
moka = { workspace = true, features = ["sync"] }
parking_lot = { workspace = true }
pin-project-lite = { workspace = true }
rama-boring = { workspace = true }
rama-boring-tokio = { workspace = true }
rama-core = { workspace = true }
rama-http-types = { workspace = true, optional = true }
rama-net = { workspace = true, features = ["tls", "http"] }
rama-ua = { workspace = true, optional = true, features = ["tls"] }
rama-utils = { workspace = true }
tokio = { workspace = true, features = ["macros", "io-std"] }
zstd = { workspace = true, optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
schannel = { workspace = true }

[dev-dependencies]
tracing-test = { workspace = true }

[lints]
workspace = true
