exclude_path = ["./target", "./docs/book/book", "./test-files"]
exclude = ["^https://api.star-history.com", "hub.docker.com", "paypal.com", "www.contributor-covenant.org", "automate.browserstack.com", "nordvpn.com", "plabayo.threadless.com"]
