[package]
name = "rama-socks5"
description = "SOCKS5 support for rama"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
keywords = ["io", "async", "socks5", "network", "rama"]
categories = ["asynchronous", "network-programming", "web-programming"]
authors = { workspace = true }
rust-version = { workspace = true }

[package.metadata.cargo-public-api-crates]
allowed = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
dns = ["dep:rama-dns", "dep:rand"]

[dependencies]
byteorder = { workspace = true }
rama-core = { workspace = true }
rama-dns = { workspace = true, optional = true }
rama-net = { workspace = true, features = ["http"] }
rama-tcp = { workspace = true, features = ["http"] }
rama-udp = { workspace = true }
rama-utils = { workspace = true }
rand = { workspace = true, optional = true }
tokio = { workspace = true }

[dev-dependencies]
tokio-test = { workspace = true }

[lints]
workspace = true
