
# cargo-vet config file

[cargo-vet]
version = "0.9"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.fermyon]
url = "https://raw.githubusercontent.com/fermyon/spin/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[[exemptions.addr2line]]
version = "0.21.0"
criteria = "safe-to-deploy"

[[exemptions.ahash]]
version = "0.8.11"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.alloc-no-stdlib]]
version = "2.0.4"
criteria = "safe-to-deploy"

[[exemptions.alloc-stdlib]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.allocator-api2]]
version = "0.2.18"
criteria = "safe-to-deploy"

[[exemptions.anstyle]]
version = "1.0.7"
criteria = "safe-to-run"

[[exemptions.argh]]
version = "0.1.12"
criteria = "safe-to-deploy"

[[exemptions.argh_derive]]
version = "0.1.12"
criteria = "safe-to-deploy"

[[exemptions.argh_shared]]
version = "0.1.12"
criteria = "safe-to-deploy"

[[exemptions.async-compression]]
version = "0.4.10"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.71"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.21.7"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.22.1"
criteria = "safe-to-deploy"

[[exemptions.bitvec]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.brotli]]
version = "6.0.0"
criteria = "safe-to-deploy"

[[exemptions.brotli-decompressor]]
version = "4.0.0"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.0.97"
criteria = "safe-to-deploy"

[[exemptions.condtype]]
version = "1.3.0"
criteria = "safe-to-run"

[[exemptions.cpufeatures]]
version = "0.2.12"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-channel]]
version = "0.5.12"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.19"
criteria = "safe-to-deploy"

[[exemptions.deranged]]
version = "0.3.11"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.divan]]
version = "0.1.14"
criteria = "safe-to-run"

[[exemptions.divan-macros]]
version = "0.1.14"
criteria = "safe-to-run"

[[exemptions.env_logger]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.3.9"
criteria = "safe-to-run"

[[exemptions.escargot]]
version = "0.5.10"
criteria = "safe-to-run"

[[exemptions.fastrand]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.flate2]]
version = "1.0.30"
criteria = "safe-to-deploy"

[[exemptions.funty]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.futures-channel]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-executor]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-io]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-lite]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.futures-macro]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.generator]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.28.1"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.14.5"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.http-range-header]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "2.2.6"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.9.0"
criteria = "safe-to-deploy"

[[exemptions.iri-string]]
version = "0.7.2"
criteria = "safe-to-deploy"

[[exemptions.jobserver]]
version = "0.1.31"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.69"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.154"
criteria = "safe-to-deploy"

[[exemptions.libfuzzer-sys]]
version = "0.4.7"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.12"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.21"
criteria = "safe-to-deploy"

[[exemptions.loom]]
version = "0.7.2"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.7.2"
criteria = "safe-to-deploy"

[[exemptions.mime_guess]]
version = "2.0.4"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.7.2"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "0.8.11"
criteria = "safe-to-deploy"

[[exemptions.num-conv]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.num-traits]]
version = "0.2.19"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.32.2"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.19.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry]]
version = "0.22.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-prometheus]]
version = "0.15.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-semantic-conventions]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry_sdk]]
version = "0.22.1"
criteria = "safe-to-deploy"

[[exemptions.ordered-float]]
version = "4.2.0"
criteria = "safe-to-deploy"

[[exemptions.parking]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.12.2"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.10"
criteria = "safe-to-deploy"

[[exemptions.pem]]
version = "3.0.4"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.14"
criteria = "safe-to-deploy"

[[exemptions.pkg-config]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.powerfmt]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.prometheus]]
version = "0.13.4"
criteria = "safe-to-deploy"

[[exemptions.protobuf]]
version = "2.28.0"
criteria = "safe-to-deploy"

[[exemptions.quickcheck]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.radium]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.rcgen]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.10.4"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.1.10"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.6"
criteria = "safe-to-deploy"

[[exemptions.regex-lite]]
version = "0.1.5"
criteria = "safe-to-run"

[[exemptions.regex-syntax]]
version = "0.6.29"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.17.8"
criteria = "safe-to-deploy"

[[exemptions.rustc-demangle]]
version = "0.1.24"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "0.38.34"
criteria = "safe-to-run"

[[exemptions.rustls]]
version = "0.23.5"
criteria = "safe-to-deploy"

[[exemptions.rustls-native-certs]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-pemfile]]
version = "2.1.2"
criteria = "safe-to-deploy"

[[exemptions.rustls-pki-types]]
version = "1.7.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.102.3"
criteria = "safe-to-deploy"

[[exemptions.schannel]]
version = "0.1.23"
criteria = "safe-to-deploy"

[[exemptions.scoped-tls]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "2.11.0"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.11.0"
criteria = "safe-to-deploy"

[[exemptions.serde_spanned]]
version = "0.6.5"
criteria = "safe-to-run"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.sha1]]
version = "0.10.6"
criteria = "safe-to-deploy"

[[exemptions.sharded-slab]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.2"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.13.2"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.5.7"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.terminal_size]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.thread_local]]
version = "1.1.8"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.36"
criteria = "safe-to-deploy"

[[exemptions.time-core]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.tinyvec_macros]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.37.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-graceful]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.26.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-stream]]
version = "0.1.15"
criteria = "safe-to-run"

[[exemptions.tokio-util]]
version = "0.7.11"
criteria = "safe-to-deploy"

[[exemptions.toml]]
version = "0.8.12"
criteria = "safe-to-run"

[[exemptions.toml_datetime]]
version = "0.6.5"
criteria = "safe-to-run"

[[exemptions.toml_edit]]
version = "0.22.12"
criteria = "safe-to-run"

[[exemptions.tracing]]
version = "0.1.40"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.27"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.32"
criteria = "safe-to-deploy"

[[exemptions.tracing-log]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.tracing-subscriber]]
version = "0.3.18"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.17.0"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.urlencoding]]
version = "2.1.3"
criteria = "safe-to-deploy"

[[exemptions.uuid]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.venndb-macros]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.92"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.92"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.92"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.92"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.92"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-util]]
version = "0.1.8"
criteria = "safe-to-run"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows]]
version = "0.54.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.winnow]]
version = "0.6.8"
criteria = "safe-to-run"

[[exemptions.wyz]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.yasna]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.7.34"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.7.34"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.7.0"
criteria = "safe-to-deploy"

[[exemptions.zstd]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.zstd-safe]]
version = "7.1.0"
criteria = "safe-to-deploy"

[[exemptions.zstd-sys]]
version = "2.0.10+zstd.1.5.6"
criteria = "safe-to-deploy"
