[package]
name = "rama-udp"
description = "UDP support for rama"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
keywords = ["io", "async", "udp", "network", "rama"]
categories = ["asynchronous", "network-programming", "web-programming"]
authors = { workspace = true }
rust-version = { workspace = true }

[lints]
workspace = true

[features]
default = []

[dependencies]
bytes = { workspace = true }
futures-core = { workspace = true }
futures-sink = { workspace = true }
futures-util = { workspace = true }
pin-project-lite = { workspace = true }
rama-core = { version = "0.2.0-alpha.10", path = "../rama-core" }
rama-net = { version = "0.2.0-alpha.10", path = "../rama-net" }
rama-utils = { version = "0.2.0-alpha.10", path = "../rama-utils" }
tokio = { workspace = true, features = ["macros", "net"] }
tokio-util = { workspace = true, features = ["net", "codec"] }
tracing = { workspace = true }

[dev-dependencies]

[package.metadata.cargo-public-api-crates]
allowed = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
