[package]
name = "rama-tcp"
description = "TCP support for rama"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
keywords = ["io", "async", "non-blocking", "futures", "tcp", "network", "rama"]
categories = ["asynchronous", "network-programming", "web-programming"]
authors = { workspace = true }
rust-version = { workspace = true }

[features]
default = []
http = ["dep:rama-http-types", "rama-net/http"]

[dependencies]
rama-core = { version = "0.2.0-alpha.3", path = "../rama-core" }
rama-http-types = { version = "0.2.0-alpha.3", path = "../rama-http-types", optional = true }
rama-net = { version = "0.2.0-alpha.3", path = "../rama-net" }
rama-utils = { version = "0.2.0-alpha.3", path = "../rama-utils" }
tokio = { workspace = true, features = ["macros", "net"] }
tracing = { workspace = true }

[dev-dependencies]

[package.metadata.cargo-public-api-crates]
allowed = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
