[package]
name = "rama-tcp"
description = "TCP support for rama"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
keywords = ["io", "async", "tcp", "network", "rama"]
categories = ["asynchronous", "network-programming", "web-programming"]
authors = { workspace = true }
rust-version = { workspace = true }

[lints]
workspace = true

[features]
default = []
http = ["dep:rama-http-types", "rama-net/http"]

[dependencies]
rama-core = { workspace = true }
rama-dns = { workspace = true }
rama-http-types = { workspace = true, optional = true }
rama-net = { workspace = true }
tokio = { workspace = true, features = ["macros", "net"] }
tracing = { workspace = true }

[dev-dependencies]

[package.metadata.cargo-public-api-crates]
allowed = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
