[package]
name = "rama-utils"
description = "utilities crate for rama"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
keywords = ["rama"]
categories = ["asynchronous", "network-programming", "web-programming"]
authors = { workspace = true }
rust-version = { workspace = true }

[package.metadata.cargo-public-api-crates]
allowed = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
parking_lot = { workspace = true }
pin-project-lite = { workspace = true }
rama-macros = { workspace = true }
serde = { workspace = true, features = ["derive"] }
smol_str = { workspace = true }
tokio = { workspace = true, features = ["time", "macros"] }

[dev-dependencies]
quickcheck = { workspace = true }
serde_json = { workspace = true }
tokio-test = { workspace = true }
trybuild = { workspace = true }

[lints]
workspace = true
