# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Plabayo.Rama.Preview
PackageVersion: 0.3.0-alpha.4
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: rama.exe
  PortableCommandAlias: rama

Installers:
- Architecture: x64
  InstallerUrl: https://github.com/plabayo/rama/releases/download/rama-0.3.0-alpha.4/rama.x86_64-pc-windows-msvc.zip
  InstallerSha256: 506CB09E8CE44F2EF78F4D3136A551403976324E8AD07A811AAD9DCA609B56AA
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/plabayo/rama/releases/download/rama-0.3.0-alpha.4/rama.aarch64-pc-windows-msvc.zip
  InstallerSha256: 903013C2D77F22A25D67A9A09E6FB121B8ACE2B7029A4FBACA0BD46635D9F59D
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64

ManifestType: installer
ManifestVersion: 1.10.0